### ISSUE TITLE
APK build with -c launches but then opens the site in Chrome!

### ISSUE THREAD

**Issue by kenchris** [manifoldjs/ManifoldJS#99] opened 2015-06-25 16:09 UTC
subject says it all

You can try an ARM APK here: https://drive.google.com/file/d/0ByMQtTUJSohfUEpaMzUxekNsZGs/view?usp=sharing

**Comment by f2bo** [comment] 2015-06-25 22:16
We can reproduce the issue with your package running in the Android emulator. However, we generated a new package with ManifoldJS using the following command line:

``` 
manifoldjs https://kenchris.github.io/#!/ -c -l debug
```
Running the generated output in the emulator launches the site inside the application, as expected. 

Looking inside your package, we notice that the config.xml file is missing an access rule, which is what's causing the site to open in the browser.

``` XML
  <allow-navigation hap-rule="yes" href="https://kenchris.github.io/*" />
```

This access rule is generated by ManifoldJS based on the target site's URL. We are not sure what caused it to be omitted. Can you please send us the exact command line that you used to generate the package? Also, can you check the platform independent config.xml at the root of your Cordova project to see if the access rule is missing there too.

Thanks.

**Comment by kenchris** [comment] 2015-06-26 09:21
I created the package like this:

`$ manifoldjs https://kenchris.github.com -p android -c`

In my config.xml I have

`<allow-navigation hap-rule="yes" href="https://kenchris.github.com/*" />`

So that doesn't seem to be missing.

**Comment by f2bo** [comment] 2015-06-26 20:25
I see what's happening. The target URL used to generate the package is https://kenchris.github.**com** but the site redirects to a different domain, http://kenchris.github.**io**. 

In this case, you need to whitelist the new domain by including a new access rule in the manifest.json file.
``` JSON
    ... 
        }
    ],
    "mjs_access_whitelist": [
        { "url": "http://kenchris.github.io/*" }
    ],
    "start_url": "https://kenchris.github.com/#!/",
```

**Comment by kenchris** [comment] 2015-06-28 13:34
Oh my bad :-(  can you make the tool warn in such cases? Would be quite useful

**Comment by f2bo** [comment] 2015-06-29 17:55
Yes. I agree. However, this cannot occur during the generation of the app. It needs to happen at runtime because it's not just the initial request that can result in the app making requests to a different domain.

I've opened a new issue (https://github.com/manifoldjs/ManifoldJS/issues/103) to track this feature. I'm closing this one.

**Closed by f2bo** 2015-06-29 17:55 UTC
